SAAS-249 Package docker image tag extaction
percona-platform/extract-docker-tag-action pull request #1
Opened 2020-09-23 20:11 UTC by palash25

2020-09-24 12:17 UTC, artemgavrilov approved these changes

2020-09-25 13:22 UTC, AlekSi requested changes

2020-09-25 13:22 UTC, AlekSi commented on action.yml
> +description: "Collect stale package versions"
Nope

2020-09-25 17:47 UTC, AlekSi approved these changes

2020-09-25 17:47 UTC, merged